### ISSUE TITLE
use nvim-treesitter module template

### ISSUE THREAD

**Issue by elianiva** [windwp/nvim-ts-autotag#1]
Hi there! I like this plugin and I've been wanting to make something similar for a while but you've done that for me, so thanks :)
I have a suggestion though, since we're depending on `nvim-treesitter`, why don't we use the [module template](https://github.com/nvim-treesitter/module-template) provided by `nvim-treesitter` for this plugin? So we can do the setup together with `nvim-treesitter` and I think that's better. An example for that is this repo https://github.com/p00f/nvim-ts-rainbow. 

```lua
-- we can do this
require'nvim-treesitter.configs'.setup {
  autotag = {
    enable = true,
    filetypes = { "html" , "xml" },
  }
  -- other nvim-treesitter config
  -- goes here
}

-- instead of separate setup like this
require('nvim-ts-closetag').setup({
  filetypes = { "html" , "xml" },
})
```

**Comment by windwp** [comment]
#15 I update it you can check readme
