### ISSUE TITLE
Inconsistent behavior

### ISSUE THREAD

**Issue by pedro757** [windwp/nvim-ts-autotag#10]
On javascriptreact autorename never works, and sometimes when I try to open a tag shows this error
![image](https://user-images.githubusercontent.com/30637426/112228193-4a0da500-8c07-11eb-8e98-d73bbb635a0d.png)

On typescriptreact neither autoclose nor autorename work

I use default config
```lua
require('nvim-ts-autotag').setup()
```

**Comment by windwp** [comment]
Sorry Can you run `:checkhealth` then run `:TSInstall javascript` and check again.

**Comment by pedro757** [comment]
This is :checkhealth output

![image](https://user-images.githubusercontent.com/30637426/112313106-e1154400-8c7d-11eb-8155-eb4eb33134fc.png)

TSInstall javascript  typescript

![image](https://user-images.githubusercontent.com/30637426/112313550-5d0f8c00-8c7e-11eb-891e-a2e890fbc8c1.png)

Maybe it's a version incompatibility, I'm using [tree-sitter-cli 0.19.4](https://www.npmjs.com/package/tree-sitter-cli) that version was published this week.

**Comment by windwp** [comment]
![image](https://user-images.githubusercontent.com/7578110/112396109-2dba5700-8d32-11eb-9986-264f5dcd7466.png)
I use a same version like you and it working 
on javascript 
- [x ] autorename
- [x ] autoclose 

on typescript 
It will not working if you not set the file type to typescriptreact(tsx) .It is because treesitter syntax of typescript don't have xml tag

If you see that error message above on javascript file can you give me that javascript code.

**Comment by pedro757** [comment]
I'm using typescriptreact(**tsx**) for this
```jsx
import React from 'react';
import Head from 'next/head';

const App = () => {

  return (
    <>
      <Head>
        <title>
          Something
        </title>
      </Head>
      <h1>
        Hello world
      </h1>
    </>
  );

}

export default App;
```
I tried on **js** **jsx** and **tsx**, These are the results:

**tsx** -> Nothing work neither autoclose nor autorename
**jsx** -> Only autoclose works
**js** -> Only autoclose works

The error on **tsx** when i try to close a div tag with >
![image](https://user-images.githubusercontent.com/30637426/112398634-fec4c680-8cda-11eb-974d-2385f96920b9.png)

I try on **js** and **jsx** autoclose is working but renaming simply does nothing

**Comment by franjs** [comment]
@windwp I have the same issue (only tried on typescript) and after some debugging I found out that `vim.bo.filetype` is returning `'typescript.tsx'`, so the `is_jsx` function is returning `false`. Adding `'typescript.tsx'` to the table fixed it for me. I can open a PR if you want.

**Comment by windwp** [comment]
Thank @franjs  
maybe another plugin set filetype to typescript.tsx. you can make a PR.

**Comment by windwp** [comment]
@pedro757 can you checkout it and test again.

**Comment by pedro757** [comment]
> @pedro757 can you checkout it and test again.

I checkout @franjs changes, Still the same, I tested on tsx, jsx and js.

**tsx** -> Nothing work neither autoclose nor autorename
**jsx** -> Only autoclose works
**js** -> Only autoclose works

**Comment by windwp** [comment]
check your filetype of tsx is typescriptreact.
Can you share a minimal config with that issue?

**Comment by franjs** [comment]
@pedro757 What do you get if you run **:lua print(vim.bo.filetype)** with those files opened?

**Comment by pedro757** [comment]
> @pedro757 What do you get if you run **:lua print(vim.bo.filetype)** with those files opened?

I tried that **typescriptreact** is the output

**Comment by pedro757** [comment]
> check your filetype of tsx is typescriptreact.
> Can you share a minimal config with that issue?

Do you want my vim config files?

**Comment by windwp** [comment]
i think it come from your plugin or your setting.
The CI test is work with that config.
https://github.com/windwp/nvim-ts-autotag/blob/main/tests/minimal.vim

**Comment by pedro757** [comment]
I tried with a minimal `init.vim` config file like this and shows the same error
![image](https://user-images.githubusercontent.com/30637426/112474103-9232e180-8d45-11eb-9538-d4e3b4a01310.png)

```vim
" My init.vim config file
call plug#begin("~/.config/nvim/plugged")
  Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
  " Plug 'windwp/nvim-ts-autotag'
  Plug 'franjs/nvim-ts-autotag'
call plug#end()

:lua <<EOF
require'nvim-treesitter.configs'.setup {
  ensure_installed = "maintained",
  highlight = {
    enable = true
  },
}

require('nvim-ts-autotag').setup()
EOF
```

**Comment by windwp** [comment]
![image](https://user-images.githubusercontent.com/7578110/112485322-63505600-8dad-11eb-8bda-ff8ca9b21bdd.png)
lol sorry i don't know what happen but can you install this plugin 
https://github.com/nvim-treesitter/playground then run command `TSPlaygroundToggle` and see it have tag jsx_openning_element.

**Comment by pedro757** [comment]
Thank you @windwp that plugin is awesome, I realized that **typescript** and **tsx** is not the same for treesitter, so I installed tsx with `TSInstall tsx` as it's describe [here](https://github.com/tree-sitter/tree-sitter-typescript) they are two different dialects.

The only problem then is autorename:

**tsx** -> Autorename is not working
**jsx** -> Autorename is not working
**js** -> Autorename is not working

**Comment by windwp** [comment]
lol You need to check it on your config. is that autorename work on html?

**Comment by pedro757** [comment]
> lol You need to check it on your config. is that autorename work on html?

I tried on html and it's the same, I think autorename is broken generally

tsx -> Autorename is not working
jsx -> Autorename is not working
js -> Autorename is not working
html -> Autorename is not working

**Comment by windwp** [comment]
@pedro757  
Did your issue of autorename is solve?

**Comment by pedro757** [comment]
No, autorename does not work

**Comment by pedro757** [comment]
I found another bug, last updates of `windwp/nvim-autopairs` and `windwp/nvim-ts-autotag` messed up autotag in `tsx` files, `jsx` still works fine when autotag, None of them work with autorename :'(

**When I disable** this plugin `windwp/nvim-autopairs` autotag works in `tsx`.

This is my autopair config
```lua
local remap = vim.api.nvim_set_keymap
local npairs = require('nvim-autopairs')
npairs.setup()

-- skip it, if you use another global object
_G.MUtils= {}

vim.g.completion_confirm_key = ""

MUtils.completion_confirm=function()
  if vim.fn.pumvisible() ~= 0  then
    if vim.fn.complete_info()["selected"] ~= -1 then
      return vim.fn["compe#confirm"](npairs.esc("<c-r>"))
    else
      return npairs.esc("<c-n><c-y>")
    end
  else
    return npairs.autopairs_cr()
  end
end

remap('i' , '<CR>','v:lua.MUtils.completion_confirm()', {expr = true , noremap = true})
remap('i' , '<c-l>','v:lua.MUtils.completion_confirm()', {expr = true , noremap = true})

```

I don't know why autorename does not work

**Comment by windwp** [comment]
Hi you can update autopairs to fix that conflict issue.

```
 return vim.fn["compe#confirm"](npairs.esc("<c-r>"))  --  it should be ==> <cr> not <c-r>
```

I don't know what happen with auto rename on your config
better try to disable another plugin or share  a minimum config of autotag when auto rename is not work then i can test on that config

**Comment by pedro757** [comment]
I updated again `nvim-autopairs` then autotag works again in `tsx`, autorename still does not work

I created this minimal config repo for you

https://github.com/pedro757/minimal-nvim-config

**Comment by pedro757** [comment]
I found the problem, this plugin autorename on `ESC`, I always use `Ctrl-c` for everything, sorry

**Comment by windwp** [comment]
yeah ctrl-c is tell vim leave insert mode without event so my plugin don't know it
i map esc to caplocks. maybe you can try 😎

**Comment by lavixta** [comment]
> yeah ctrl-c is tell vim leave insert mode without event so my plugin don't know it
> i map esc to caplocks. maybe you can try 😎

Should i map <C-c> to <ESC> . Will it cause any error ?

**Comment by pedro757** [comment]
> > yeah ctrl-c is tell vim leave insert mode without event so my plugin don't know it
> > i map esc to caplocks. maybe you can try 😎
> 
> Should i map <C-c> to <ESC> . Will it cause any error ? 

I did that, and it's ok for me I haven't need ever to leave insert mode without issuing an event
