### ISSUE TITLE
Breaks Luasnip for triggers ending in '>'

### ISSUE THREAD

**Issue by ribru17** [windwp/nvim-ts-autotag#102]
See [this issue](https://github.com/L3MON4D3/LuaSnip/issues/865). This plugin causes Luasnip snippets to not autoexpand when their trigger ends in the `>` character.

**Comment by windwp** [comment]
you should choose  1 or write your own mapping function to combine both plugin

**Comment by yioneko** [comment]
Same issue here. I make [a dirty hack](https://github.com/yioneko/nvim-ts-autotag/commit/05baecea3a2b316375cc66251d99274e5dd8b064) to avoid '>' key mapping.

**Comment by ribru17** [comment]
To anyone facing this issue, add this after setting up your Luasnip:
```lua
local autotag = require('nvim-ts-autotag.internal')
vim.keymap.set('i', '>', function()
  local row, col = unpack(vim.api.nvim_win_get_cursor(0))
  vim.api.nvim_buf_set_text(0, row - 1, col, row - 1, col, { '>' })
  autotag.close_tag()
  vim.api.nvim_win_set_cursor(0, { row, col + 1 })
  ls.expand_auto()
end, { remap = false })
```
