### ISSUE TITLE
nvim-ts-autoblock, automatically close Ruby blocks like Tim Pope's endwise

### ISSUE THREAD

**Issue by bluz71** [windwp/nvim-ts-autotag#11]
Hello,

Just brainstorming, feel free to instantly close this if you are not interested.

When Treesitter is in effect for Ruby Tim Pope's [endwise](https://github.com/tpope/vim-endwise) does not work as noted [in this issue](https://github.com/nvim-treesitter/nvim-treesitter/issues/703).

Is it something you could create since you already have created autotag. If not, just close this.

Best regards.

**Comment by windwp** [comment]
https://github.com/windwp/nvim-autopairs/blob/master/doc/endwise.md

read that to make your rule on autopair with endwise

**Comment by bluz71** [comment]
Thanks for that.
Looks like it will do the job.
Very soon I will experiment.
