### ISSUE TITLE
TSX not working

### ISSUE THREAD

**Issue by MincoMK** [windwp/nvim-ts-autotag#112]
HTML file is working but JSX or TSX aren't working. How to fix?

**Comment by yagiziskirik** [comment]
I also have the same issue, tried to `:TSInstall html`, `:TSInstall javascript` and `:TSInstall typescript`. It is also configured in the *init.lua* file as you described in the README file. HTML files work just fine but JSX or TSX files don't work as expected. I can provide any additional details about the configuration that I have as well.

I will try to find a solution and issue a pull request or share the solution if I can. Amazing add-on!

**Comment by yagiziskirik** [comment]
Found the solution! #106 stated that code required is `:TSInstall tsx`. This can be added to the README file as well.
