### ISSUE TITLE
Remap input from ESC to Control + c to rename tags

### ISSUE THREAD

**Issue by rafa-thayto** [windwp/nvim-ts-autotag#117]
How can I auto-rename tags with `Control + c` instead of `ESC`?

I've not found any related issues. Anyone can help me?

**Comment by molvrr** [comment]
Hey @rafa-thayto, I believe this is related to how [`CTRL-C`](https://neovim.io/doc/user/insert.html#insert.txt) works in Neovim. `CTRL-C` doesn't trigger `InsertLeave` events (which is the event nvim-ts-autotag uses for renaming tags). Remapping `CTRL-C` to `ESC` in Insert Mode might be what you're looking for.

**Comment by rafa-thayto** [comment]
> Hey @rafa-thayto, I think this is related to how [`CTRL-C`](https://neovim.io/doc/user/insert.html#insert.txt) works in Neovim. `CTRL-C` doesn't trigger `InsertLeave` events (which is the event nvim-ts-autotag uses for renaming tags). Remapping `CTRL-C` to `ESC` in Insert Mode might be what you're looking for.

Sad... but thank you for the answer!
