### ISSUE TITLE
`nvim-ts-autotag` stops working after certain commands provided by `barbar.nvim` are run

### ISSUE THREAD

**Issue by anthony-S93** [windwp/nvim-ts-autotag#121]
I've already opened an [issue](https://github.com/romgrk/barbar.nvim/issues/510) at `barbar.nvim` (romgrk/barbar.nvim/#510) but I decided to open an issue here as well. 

Here is the gist of the issue: `autotag` simply stops working every time I close a buffer with `BufferClose` and `BufferWipeout` (those two commands are defined by `barbar.nvim`)

So if I have two buffers opened `foo1` and `foo2`, closing `foo2` with `BufferWipeout` will cause autotag to stop working in `foo1`. I have tried closing the buffer with the native `:bw` command instead of `:BufferWipeout`, but it appears that the native command does not cause autotag to fail. For videos demonstrating this issue, please refer to the [issue](https://github.com/romgrk/barbar.nvim/issues/510) opened at `barbar.nvim`.

**Comment by guivazcabral** [comment]
I'm using mini.starter and mini.sessions and when it calls BufferWipeout also makes autotag stop working. closing buffers with `:Bdelete!` also has the same effect

**Comment by nsoufian** [comment]
I confirm that autotag stop working after closing a non active buffer using ` :bwipeout`
