### ISSUE TITLE
Svelte Autorename Issue: Only Works When HTML is Above the Script Block

### ISSUE THREAD

**Issue by alcibiadesc** [windwp/nvim-ts-autotag#122]
**Describe the bug**
The autorename feature of nvim-ts-autotag doesn't work as expected when the HTML is below the script block in Svelte files. The autorename only works correctly when the HTML is above the script block.

**To Reproduce**
1. Open a Svelte file in lunarvim.
2. Place the HTML block below the script block.
3. Try to rename a tag in the HTML block.
4. Notice that the corresponding closing tag doesn't get renamed.

**Expected behavior**
I expect the corresponding closing tag to get renamed, regardless of whether the HTML block is above or below the script block in Svelte files.

GIF:
![error](https://github.com/windwp/nvim-ts-autotag/assets/62911544/99f0312b-c25b-43c2-8677-4316e10805cc)

**Comment by alcibiadesc** [comment]
Update: if you put a commented script at the end of the svelte document, you will not have the problem, although it is not practical at all


![randomfix](https://github.com/windwp/nvim-ts-autotag/assets/62911544/679c18cb-f8b8-4704-a57e-0c2fae284f76)

**Comment by m-gail** [comment]
I have the same problem, though it seems like it happens on the last tag in the file in general. It also only happens, if the tag is on a single line.

For example:

```svelte
<script>
  export let data;
</script>

<div>{data}</div> <!-- renaming this causes the issue -->
```

```svelte
<script>
  export let data;
</script>

<div>  <!-- renaming this does not cause the issue -->
  {data}
</div>
```

**Comment by cassepipe** [comment]
Wow congrats on finding out that if you put the html above the script, it works, I  thought it just didn't work for svelte files.

**Comment by TheBlckbird** [comment]
> 



> Wow congrats on finding out that if you put the html above the script, it works, I thought it just didn't work for svelte files.
> 
> I confirm I have the same problem. It's totally useless then **I am not event sure svelte accepts a script block under the component's body** and even if it could, people reading your code wouldn't be very happy about it

It does, but you shouldn't do it as it's against the coventions.

**Comment by TheBlckbird** [comment]
And prettier automatically formats the component in that way
