### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by s1nistr4** [windwp/nvim-ts-autotag#123]
I follow the instructions in the readme, as well as have treesitter installed, then I try renaming tags and nothing happens.

**Comment by iam-arnab** [comment]
Do you have treesitter parser for html installed?

**Comment by bepnos** [comment]
Same here downloaded it using Packer, show up on PackerSync as properly installed. Added the lines in my treesitter.lua file yet it does not work on any html files I open.

**Comment by wambldor** [comment]
Unfortunately, the plugin does not work for me either. I use NvChad, so the lazy.nvim, and the following configuration for treesitter and nvim-ts-autoclose:
 
 ```
 {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        -- defaults
        "vim",
        "lua",
        "markdown",

        "html",
        "css",
        "javascript",
        "typescript",
        "json",
        "c_sharp",
        "sql",
        "yaml",
        "xml",
        "tsx",
      },
      autotag = {
        enable = true
      },
    },
  },
  {
    "windwp/nvim-ts-autotag",
    dependencies = "nvim-treesitter/nvim-treesitter",
    event = "VeryLazy",
    config = function()
      require("nvim-ts-autotag").setup()
    end,
  },
  ```
  
  Especially important to me would be the automatic closing of xml tags.

**Comment by harrismcc** [comment]
Having a similar issue installing, also with lazy.nvim

**Comment by hinell** [comment]
Works for me in html and tsx/jsx files. 

Replacing tag name works with quirks....

**Comment by hinell** [comment]
Works for me in html and tsx/jsx files. 

Renmaing tag back from `<xyz>` to `<div>` works with quirks....
