### ISSUE TITLE
Autocompletion Incorrectly Expands Self-Closing Tags in React JSX

### ISSUE THREAD

**Issue by Innei** [windwp/nvim-ts-autotag#124]
Hello,

I'm experiencing an issue with the nvim-ts-autotag plugin where the autocompletion feature is not correctly expanding self-closing tags.

## Current Behavior:
When I type `<Img /`, the plugin automatically completes it as `<Img /Img>`, which is not the expected behavior.

## Expected Behavior:
The expected behavior is for the plugin to complete the tag as `<Img />`.

## Steps to Reproduce:

Open a .jsx or .tsx file.
Start typing a self-closing tag, for example: `<Img /`.
The plugin incorrectly autocompletes the tag as `<Img /Img>`.

## Env
```
    ● nvim-ts-autotag 1.29ms  start
        dir    /Users/innei/.local/share/nvim/lazy/nvim-ts-autotag
        url    https://github.com/windwp/nvim-ts-autotag
        branch main
        commit 6be1192
        readme README.md

```

**Comment by 2Senn** [comment]
Having the same issue. Any fix?

**Comment by nomnivore** [comment]
I'm also facing this problem. I think that conditionally turning off the `close_on_slash` feature while inside of a tag element should suffice.

**Comment by 2Senn** [comment]
That kinda solves the problem but it sorta created a new issue. The functionality for closing tags like: 

<NavigationStack.Navigator> 

broke. Basically it does not create a closed tag for it anymore which is sadge.

**Comment by doganalper** [comment]
@2Senn I haven't turned off `close_on_slash` feature yet and I'm facing issue you mentioned above. I don't think turning off that feature caused it.

**Comment by gonstoll** [comment]
Getting the same here 😔 turning off `close_on_slash` works as a temporary fix. Hope this gets sorted out soon!

**Comment by andelkocvjetkovic** [comment]
I'm having the same issues.

**Comment by AnthonyDugarte** [comment]
Having the same issues.

**Comment by alevor657** [comment]
Same issues here

**Comment by kuator** [comment]
Same issue

**Comment by kuator** [comment]
Alternative solution: https://github.com/aca/emmet-ls/issues/69

**Comment by drew-harris** [comment]
Also having the same issue. Feels like it started happening out of no where

**Comment by sajadspeed** [comment]
Same here.
