### ISSUE TITLE
hbs support

### ISSUE THREAD

**Issue by ziulev** [windwp/nvim-ts-autotag#13]
Would love to see https://handlebarsjs.com/ support 🚀

**Comment by pedro757** [comment]
This plugin depends on [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) plugin, so if there's no support [there](https://github.com/nvim-treesitter/nvim-treesitter#supported-languages), there's nothing to do here.

**Comment by ziulev** [comment]
@pedro757 Seems like tree sitter [supports](https://github.com/nvim-treesitter/nvim-treesitter/issues/1113) `hbs`

**Comment by windwp** [comment]
fixed
