### ISSUE TITLE
Not working with Tags that have `.` in the middle

### ISSUE THREAD

**Issue by howarddo2208** [windwp/nvim-ts-autotag#138]
I'm using `styled-components` and it's not working with those tags, as in the video below

https://github.com/windwp/nvim-ts-autotag/assets/62332195/e162a4e9-33be-4e65-a23c-3586e0cfe7d6

**Comment by amirhhashemi** [comment]
I have the same problem with `framer-motion` and it's really annoying:
```tsx
import { motion } from "framer-motion"

const Component = () => {
  return <motion.div></motion.div> // not working here
}
```

**Comment by howarddo2208** [comment]
> You can use 'surround' way.

Yeah, it's a workaround for that. But I think there should be an update for this use case.

**Comment by amirhhashemi** [comment]
Looks like it's been fixed in the latest version.

**Comment by howarddo2208** [comment]
> Looks like it's been fixed in the latest version.

yeah, I will close the issue for now.
