### ISSUE TITLE
autorename does not work but autoclose does???

### ISSUE THREAD

**Issue by ruahman** [windwp/nvim-ts-autotag#140]
here is a gif of a screen recording. 
![autorename](https://github.com/windwp/nvim-ts-autotag/assets/360398/cf5c4736-9ea3-4e7b-8e8c-41cfde42f2f8)

this is what my setup looks like
![image](https://github.com/windwp/nvim-ts-autotag/assets/360398/3f6d98a8-1548-4368-bd0e-fdfb252935ed)

this is the repo where I have my nvim configuration
https://github.com/ruahman/neovim.git

I've tried searching through the recorded Issues.  
I wasn't able to find anything.

i like this plug in.  the autoclose feature works for me, it's just not autorenaming.
any help or suggestions would be appreciated

**Comment by Azoth128** [comment]
+1, having the exact same issue

**Comment by scutta2000** [comment]
> +1, having the exact same issue
> 
> EDIT: I noticed, that rename of other tags, like `h3`or `span`does work. Maybe the congfig degault of `skip_tags` in the readme is not up to date.

Have the same issue even in the latest version
