### ISSUE TITLE
Plugin Stops Working on Current Buffer After Closing Other Buffers.

### ISSUE THREAD

**Issue by nsoufian** [windwp/nvim-ts-autotag#143]
**Problem:**

I've encountered an issue with the `nvim-ts-autotag` plugin that I'd like to report. The problem occurs when using the plugin alongside a buffer-closing mapping. After executing a mapping to close all buffers except the current one, the `nvim-ts-autotag` functionality ceases to work in the current buffer. This issue seems to affect the plugin's ability to automatically close tags.

**Steps to Reproduce:**

1. Install and configure `nvim-ts-autotag` for automatic tag closing in Neovim.
2. Create multiple buffers with HTML, XML, or JSX content.
3. Execute a mapping or command to close all buffers except the current one

**Expected Behavior:**

The `nvim-ts-autotag` plugin should continue to function as expected in the current buffer, automatically closing tags for supported languages.

**Actual Behavior:**

After closing other buffers as described in the steps to reproduce, the `nvim-ts-autotag` plugin stops working in the current buffer. It no longer closes tags automatically.

**Comment by nsoufian** [comment]
@windwp can we re-open this issue ?

**Comment by krehwell** [comment]
happened to me too. I think this issue should be reopened

**Comment by PriceHiller** [comment]
Hey folks if you're still having issues, I've begun maintaining a fork over @ https://github.com/PriceHiller/nvim-ts-autotag until windwp is active again.

Give it a shot and if it's still not working then open an issue over there and I'll investigate 🙂.
