### ISSUE TITLE
Autotag inserts tag name incorrectly after trailing slash

### ISSUE THREAD

**Issue by vjrasane** [windwp/nvim-ts-autotag#151]
![autotag bug](https://github.com/windwp/nvim-ts-autotag/assets/3148501/57a7d960-d2be-42af-b24c-74fb19fa36a7)

I noticed some weird behavior when trying to insert self closing tags in JSX. After placing the trailing slash autotag inserts the tag name after it for some reason. I've verified that the problem only occurs with autotag enabled, but it could of course be caused by some interaction with other autocomplete plugins for example. I do not have a minimal repro at this time, but I can provide the full nvim config if needed.

Treesitter version: master commit 3da5cfb
Autotag version: main commit 6be1192
Nvim version info:
```lua
{
  api_compatible = 0,
  api_level = 11,
  api_prerelease = false,
  major = 0,
  minor = 9,
  patch = 1,
  prerelease = false
}
```

**Comment by maxmaio** [comment]
having same issue

**Comment by Kachajal** [comment]
Same issue here. For now I've worked around this by setting 
`    enable_close_on_slash = false`
in the treesitter autotag config.

**Comment by amirhhashemi** [comment]
Looks like it's been fixed in the latest version.
