### ISSUE TITLE
Config JSX Fragments

### ISSUE THREAD

**Issue by pojokcodeid** [windwp/nvim-ts-autotag#160]
Hai 

How to config auto close jsx fragment tag (<></>)
for other tag already ok

Thanks

**Comment by PriceHiller** [comment]
Hey folks if you're still having issues, I've begun maintaining a fork over @ https://github.com/PriceHiller/nvim-ts-autotag until windwp is active again.

Give it a shot and if it's still not working then open an issue over there and I'll investigate 🙂.

I'm not familiar with jsx/tsx, so if you have an example file you can point me at I can take a look and try to implement support on my fork (if it doesn't already work).
