### ISSUE TITLE
With lazy, works in html files, doesn't work in js/jsx files

### ISSUE THREAD

**Issue by aaannestad** [windwp/nvim-ts-autotag#161]
I've been able to install nvim-ts-autotag with lazy.vim, and it works totally fine in html files, but inside a js or jsx file with React code it does nothing.

In the nvim-treesitter config file I have this for autotagging:
```
				autotag = { 
					enable = true,
					enable_rename = true,
					enable_close = true,
					enable_close_on_slash = true,
					filetypes = { "html" , "xml", "js", "jsx"},	
				},
```

but it still only works inside html files.

What do I need to change to make this work?

**Comment by manasveer6** [comment]
I had the same issue, try including "javascriptreact" as well in the filetypes. That seemed to work for me. Also replace "js" with "javascript"

**Comment by aaannestad** [comment]
That seems to have done it, though it doesn't seem to work everywhere I'd expect it to. Thank you!

**Comment by yasirjanjua** [comment]
The plugin doesn't work at all on any extension for me. Did a fresh installation with lazy.vim and followed all the hacks/suggestions mentioned in other threads.

**Comment by lazypool** [comment]
Same here.

**Comment by PriceHiller** [comment]
Hey folks if you're still having issues, I've begun maintaining a fork over @ https://github.com/PriceHiller/nvim-ts-autotag until windwp is active again.

Give it a shot and if it's still not working then open an issue over there and I'll investigate 🙂.

**Comment by manu-xo5** [comment]
Hi 👋

First of all, thanks for maintaining this plugin — it’s super helpful!

While setting up nvim-ts-autotag, I ran into this issue where autotag worked in HTML but not in .tsx files. The README could be clearer about the setup needed for React/TSX users.

```lua
require("nvim-treesitter.configs").setup {
  ensure_installed = {
    "html", "javascript", "typescript", "tsx", -- include tsx
  },
  highlight = { enable = true },
}
```
