### ISSUE TITLE
Doesn't close tags in XML

### ISSUE THREAD

**Issue by jonathanmorris180** [windwp/nvim-ts-autotag#163]
Thanks for your work on this plugin! 

I've been trying to get the auto-closing to work for xml files (this is important for Java projects since working with the POM can be a pain otherwise) but it doesn't seem to work. [Here](https://github.com/jonathanmorris180/nvim/blob/main/lua/jonathan/plugins/nvim-treesitter.lua) is my nvim-treesitter config.

Please let me know if more info is needed.

**Comment by TXPGhost** [comment]
Having the same issue. Works for HTML but not XML.

**Comment by jonathanmorris180** [comment]
@PriceHiller will you be able to get the above PR merged?

**Comment by PriceHiller** [comment]
> @PriceHiller will you be able to get the above PR merged?

If my PR is looked at, then yes. As far as I can tell my patch works as expected. 

I'll ping on the PR to windwp. He may have missed this/lacked time to really look. 

If it doesn't get looked at then I'll probably end up maintaining some small patches and whatnot on my fork as I encounter bugs.

**Comment by PriceHiller** [comment]
Unfortunately it appears @windwp hasn't responded to my ping in a week in any way.

For anyone interested (like @jonathanmorris180), I'll be maintaining a fork over @ https://github.com/PriceHiller/nvim-ts-autotag/ with some of the PRs open here merged later today until such a time where @windwp is able to continue working on this plugin.

I hope they're doing ok. Once (or if) they come back, I'll look into merging my fork back here. Please ping me when you're back @windwp, the plugin kicks ass and life sometimes hits hard. No problem if you're gone for a bit, it's a free plugin after all 😉.

**Comment by PriceHiller** [comment]
Will be closed by #173

**Comment by PriceHiller** [comment]
Resolved by #173. Please do not use my fork anymore -- this repository is still being maintained by windwp and I am also now a maintainer assisting them.

If XML tags still don't work, ping me and I'll reopen and investigate, thanks!
