### ISSUE TITLE
Does not auto tag when mapping in .astro file but works with .tsx

### ISSUE THREAD

**Issue by JNer1** [windwp/nvim-ts-autotag#168]
When I type an element while mapping in a `.astro` file, the auto-tagging does not work.

In the example below, typing out the `<li>` inside the `map` method does not trigger the auto-tagging. However, this works fine in a `.tsx` file.

```astro
---
import Layout from "../layouts/Layout.astro";
import { publications } from "../publications";
---

<Layout title="Publications">
  <main class="mx-auto max-w-5xl p-8">
    <ul class="flex flex-col gap-4">
      {publications.map((pub) => <li>{pub.title}</li>)}
    </ul>
  </main>
</Layout>

```

## Config

Neovim Version: v0.9.5
Package Manager: Lazy

```lua
return {
	"windwp/nvim-ts-autotag",
	opts = {
		enable_close_on_slash = false,
	},
}
```

**Comment by PriceHiller** [comment]
Hello, this should be resolved with the merging of #173.

I'll be closing this as a result. If you're still facing issues, please ping me and I'll reopen this.

Thanks 🙂
