### ISSUE TITLE
Error since update: `nvim-ts-autotag` claims support for `0.9.5` using `0.10.0` exclusive functions

### ISSUE THREAD

**Issue by Emille1723** [windwp/nvim-ts-autotag#174]
OS: Manjaro Xfce
Nvim Version: 0.9.5

Steps:
- Remove as a dependency of nvim-treesitter
- Setup nvim-ts-autotag with its default config
- Disable treesitter settings for autotag (error also occurred when I toggled it back on)
- I don't have fzf-lua calling autotag, so not sure why it's referencing it

Any help is appreciated, thank you

![nvim-ts-autotag](https://github.com/windwp/nvim-ts-autotag/assets/22212587/4287f0e2-0fb6-4e96-a664-c49d1d2d6eec)

**Comment by PriceHiller** [comment]
Ah, that's my fault 😅 . I'll fix it. Give me 10 minutes.

**Comment by windwp** [comment]
hi i create  branch nvim_0.9 . you can temporally use it.
 https://github.com/windwp/nvim-ts-autotag/tree/nvim_0.9

**Comment by PriceHiller** [comment]
Made a PR that *partially* resolves it, some tests are still relying on `vim.islist`, I'll make a follow up to further fix the tests then close this then.

**Comment by PriceHiller** [comment]
Latest force push covers tests as well.

I'll get Neovim `0.9.5` added to the CI later so this doesn't happen again. My bad.

**Comment by PriceHiller** [comment]
Ping me if you're still facing errors. I'll reopen and continue investigation.

When I use `0.9.5` locally, it's working as expected for me.

**Comment by Emille1723** [comment]
Hey, I haven't experienced the error and the plugin is working as expected so far since the patch. Thank you.
