### ISSUE TITLE
Doesn't work even though installed + setup + autotag enabled

### ISSUE THREAD

**Issue by KMint1819** [windwp/nvim-ts-autotag#186]
Sorry to bother with a niche problem but I could never get this plugin working after hours of researching.
I'm using `lazy.nvim` + `nvim 0.9.5` and AFAIK to enable this plugin I'll have to:
1. Enable autotag in treesitter
```lua
local options = {
  ensure_installed = { "lua", "vim", "vimdoc" },

  highlight = {
    enable = true,
    use_languagetree = true,
  },

  autotag = {
    enable = true,
  },

  indent = { enable = true },
}
return options
```
2. Install through `lazy.nvim` and setup
```lua
  {
    "windwp/nvim-ts-autotag",
    lazy = false,
    dependencies = "nvim-treesitter/nvim-treesitter",
    config = function()
      require 'nvim-ts-autotag'.setup()
    end,
  },

```
Am I missing anything? You can see my config file [here](https://github.com/KMint1819/nvimda/tree/autotag)
I'm mainly working on `.jsx` files but `html` files don't work as well.

**Comment by PriceHiller** [comment]
Alright, this has become enough of a problem that I need to add documentation around this 😅.

So for your case, try adding `html` and other languages you want autotag support in to your `ensure_installed` section for `nvim-treesitter`.

Alternatively, you can set `auto_install = true` for `nvim-treesitter` which will install the parsers as needed. Autotag won't/can't work without the associated treesitter parser installed for a given language.

See https://github.com/windwp/nvim-ts-autotag/issues/64#issuecomment-2119580720 for a response to a previous issue of this sort.

I'll keep this issue open and create a PR to update documentation and close it from there.

**Comment by KMint1819** [comment]
omg that response was quick :100: 
Setting `auto_install = true` shows this error:
```bash 
Nvim Treesitter Setup is deprecated, use `require('nvim-ts-autotag').setup()` instead.                                                            
This feature will be removed in nvim-ts-autotag version 1.0.0  
```
but setting `ensure_installed` works. Thanks!

**Comment by PriceHiller** [comment]
>  Setting auto_install = true shows this error:

Remove [these lines](https://github.com/KMint1819/nvimda/blob/6a6ffd09340b2ed347402be2c92b80adfaa308de/lua/plugins/configs/treesitter.lua#L45-L47) from your config.

We no longer use `nvim-treesitter` modules.

Use the plain `require("nvim-ts-autotag").setup` method.

**Comment by KMint1819** [comment]
That was it!!! :tada: :tada:
