### ISSUE TITLE
bug: Rename stops working after switching to another buffer

### ISSUE THREAD

**Issue by isak102** [windwp/nvim-ts-autotag#189]
I have encountered a bug where the rename functionality stops working after switching to another buffer. The auto-close still works as expected however. Below is a demo of the issue happening:

https://github.com/windwp/nvim-ts-autotag/assets/90389894/8821b93a-5970-4239-b2a9-217bde5f969f

I am using `lazy.nvim` and this is how I setup the plugin:

```lua
return {
    "windwp/nvim-ts-autotag",
    lazy = false,
    config = function()
        require("nvim-ts-autotag").setup()
    end,
}
```

I am on commit `6eb4120a1aadef07ac312f1c4bc6456712220007`

**Comment by PriceHiller** [comment]
Huh. I'll look into this later today or tomorrow when I have a moment.

Thought I resolved a similar bug to this previously, but clearly something isn't attaching correctly.

**Comment by PriceHiller** [comment]
Hey @isak102 it's definitely *not* today or tomorrow, but I just pushed a commit that hopefully resolves this.

Check it out and let me know. If I don't get a response I'll assume it's been resolved and close this issue after a week or so.

Thanks 🙂

**Comment by isak102** [comment]
No worries. It works, thanks!
