### ISSUE TITLE
Nvim Treesitter Setup is deprecated

### ISSUE THREAD

**Issue by cipherlogs** [windwp/nvim-ts-autotag#191]
When I open nvim and use `Shift-K` I get this error!

what could be the problem?

```
Nvim Treesitter Setup is deprecated, use `require('nvim-ts-autotag').setup()` inste
ad.
Feature will be removed in nvim-ts-autotag 1.0.0
```

**Comment by PriceHiller** [comment]
Repasting from another comment (https://github.com/windwp/nvim-ts-autotag/issues/192#issuecomment-2158966026):
> That means you still have a treesitter module setup method somewhere in your config.
> 
> Look for something like `require("nvim-treesitter.configs").setup` and remove the related autotag section from it.
> 
> Feel free to reopen this if you can confirm you're not setting up via `nvim-treesitter` at all and still facing this.
> 
> Thanks 🙂

If you're still having this issue, please head over to https://github.com/windwp/nvim-ts-autotag/issues/192#issuecomment-2158966026 and ping me and I'll reopen it.

**Comment by cipherlogs** [comment]
@PriceHiller I'm using nvChad, and I don't have any `require("nvim-treesitter.configs").setup`.

I don't know where this issue is coming from!

**Comment by cipherlogs** [comment]
I took a look at your `dot` files, found out that you are using `require("nvim-treesitter.configs").setup` too!

I'm confused what's this new way that we have to use?

**Comment by PriceHiller** [comment]
So `require("nvim-treesitter.configs").setup` is going to be removed/deprecated once Neovim 0.11 hits stable. 

Seeing as you're using `nvchad`, perhaps `nvchad` sets up `nvim-ts-autotag` via the `require("nvim-treesitter.configs").setup` which is causing the issue.

Basically remove anything that looks like:

```lua
require("nvim-treesitter.configs).setup({
  autotag = {
    enable = true
  }
})
```

> I'm confused what's this new way that we have to use?

New way is just to do:
```lua
require("nvim-ts-autotag").setup({
    opts = {
        enable_close_on_slash = true,
    },
})
```

**Comment by cipherlogs** [comment]
Thank you!
