### ISSUE TITLE
Nvim Treesitter Setup is deprecated

### ISSUE THREAD

**Issue by savchenko** [windwp/nvim-ts-autotag#192]
The error is returned despite using the recommended setup method.
Using latest versions of the plugin, treesitter and nVim (v0.10.0).

### Configuration

```lua
{
    url = 'https://github.com/windwp/nvim-ts-autotag',
    config = function()
        require('nvim-ts-autotag').setup({
            opts = {
                enable_close = true,
                enable_rename = true,
                enable_close_on_slash = true
            }
        })
    end
}
```

### Error

```
Nvim Treesitter Setup is deprecated, use `require('nvim-ts-autotag').setup()` instead.                                                                                                          
Feature will be removed in nvim-ts-autotag 1.0.0                                                                                                                                                
stack traceback:                                                                                                                                                                                
        .../share/nvim/lazy/nvim-ts-autotag/lua/nvim-ts-autotag.lua:15: in function 'attach'                                                                                                    
        ...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:509: in function 'attach_module'                                                                                            
        ...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:532: in function 'reattach_module'                                                                                          
        ...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:133: in function <...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:132>                                          
        [C]: in function 'nvim_cmd'                                                                                                                                                             
        /usr/share/nvim/runtime/filetype.lua:36: in function </usr/share/nvim/runtime/filetype.lua:35>                                                                                          
        [C]: in function 'nvim_buf_call'                                                                                                                                                        
        /usr/share/nvim/runtime/filetype.lua:35: in function </usr/share/nvim/runtime/filetype.lua:10> 
```

**Comment by PriceHiller** [comment]
That means you still have a treesitter module setup method somewhere in your config.

Look for something like `require("nvim-treesitter.configs").setup` and remove the related autotag section from it.

Feel free to reopen this if you can confirm you're not setting up via `nvim-treesitter` at all and still facing this.

Thanks 🙂

**Comment by marcusluis-s** [comment]
@cool-pants Hi. I was facing the same probem and to fix this problem I just set autotag to false on `treesitter` config:

```
autotag = {
    enable = false,
},
```

This is my `treesitter` file:

```
return {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    config = function()
        require("nvim-treesitter.configs").setup {
            ensure_installed = {
                "lua",
                "luadoc",
                "bash",
                "c",
                "cmake",
                "make",
                "html",
                "css",
                "scss",
                "markdown",
                "markdown_inline",
                "vim",
                "vimdoc",
                "query",
                "dockerfile",
                "gitignore",
                "javascript",
                "jsdoc",
                "typescript",
                "tsx",
                "python",
                "diff",
            },
            -- Autoinstall parsers that are not installed
            auto_install = true,
            autopairs = {
                enable = true,
            },
            autotag = {
                enable = false,
            },
            endwise = {
                enable = true,
            },
            highlight = {
                enable = true,
            },
            indent = {
                enable = true,
            },
            incremental_selection = {
                enable = true,
                keymaps = {
                    init_selection = "gnn",
                    node_incremental = "grn",
                    scope_incremental = "grc",
                    node_decremental = "grm",
                },
            },
        }
    end
}
```

**Comment by mainak-affinsys** [comment]
> @cool-pants Hi. I was facing the same probem and to fix this problem I just set autotag to false on `treesitter` config:
> 
> ```
> autotag = {
>     enable = false,
> },
> ```
> 
> This is my `treesitter` file:
> 
> ```
> return {
>     "nvim-treesitter/nvim-treesitter",
>     build = ":TSUpdate",
>     config = function()
>         require("nvim-treesitter.configs").setup {
>             ensure_installed = {
>                 "lua",
>                 "luadoc",
>                 "bash",
>                 "c",
>                 "cmake",
>                 "make",
>                 "html",
>                 "css",
>                 "scss",
>                 "markdown",
>                 "markdown_inline",
>                 "vim",
>                 "vimdoc",
>                 "query",
>                 "dockerfile",
>                 "gitignore",
>                 "javascript",
>                 "jsdoc",
>                 "typescript",
>                 "tsx",
>                 "python",
>                 "diff",
>             },
>             -- Autoinstall parsers that are not installed
>             auto_install = true,
>             autopairs = {
>                 enable = true,
>             },
>             autotag = {
>                 enable = false,
>             },
>             endwise = {
>                 enable = true,
>             },
>             highlight = {
>                 enable = true,
>             },
>             indent = {
>                 enable = true,
>             },
>             incremental_selection = {
>                 enable = true,
>                 keymaps = {
>                     init_selection = "gnn",
>                     node_incremental = "grn",
>                     scope_incremental = "grc",
>                     node_decremental = "grm",
>                 },
>             },
>         }
>     end
> }
> ```

This seems to solve my issue as well. Thanks 🫡

**Comment by terrancecorley** [comment]
Any idea on how to get the treesitter :TSModuleInfo to show the auto tags as enabled with a green checkmark? They work given the instructions here but I still see them as disabled in the TSModuleInfo UI.

## treesitter.lua
```
return {
  "nvim-treesitter/nvim-treesitter",
  event = { "BufReadPre", "BufNewFile" },
  build = ":TSUpdate",
  dependencies = {
    "windwp/nvim-ts-autotag",
  },
  config = function()
    -- configure treesitter
    require'nvim-treesitter.configs'.setup {
      highlight = {
        enable = true,
      },
      -- enable indentation
      indent = { enable = true },
      -- ensure these language parsers are installed
      ensure_installed = {
        "bash",
        "c",
        "css",
        "dockerfile",
        "gitignore",
        "html",
        "json",
        "javascript",
        "lua",
        "markdown",
        "markdown_inline",
        "query",
        "scss",
        "sql",
        "tsx",
        "typescript",
        "vim",
        "vimdoc",
        "yaml",
      },
      incremental_selection = {
        enable = true,
        keymaps = {
          init_selection = "<C-space>",
          node_incremental = "<C-space>",
          scope_incremental = false,
          node_decremental = "<bs>",
        },
      },
    }

    -- enables auto tagging
    require('nvim-ts-autotag').setup()
  end,
}
```

## :TSModuleInfo

![Image](https://github.com/user-attachments/assets/5e99a6f0-1675-49bd-8730-ccdb2e59b03b)
