### ISSUE TITLE
Closign tag сauses a lot of errors

### ISSUE THREAD

**Issue by timsofteng** [windwp/nvim-ts-autotag#20]
Hello. I've notice that closing tags causes a lot of error in virtual text until leaving from insert mode to normal. Take a look into screencast please:

https://user-images.githubusercontent.com/51912173/122195848-62582d80-ce9f-11eb-9134-fa1d1ba40e52.mp4

Any way to prevent it?

**Comment by windwp** [comment]
#19 duplicate
