### ISSUE TITLE
Renaming XML tag doesn't work

### ISSUE THREAD

**Issue by julianbopp** [windwp/nvim-ts-autotag#207]
Hello, 

renaming tags does not work in XML files:

https://github.com/user-attachments/assets/a0c9e701-3b84-464e-966b-6f5816e562c3

My nvim-ts-autotag config:
```
require('nvim-ts-autotag').setup {
      opts = {
        -- Defaults
        enable_close = true, -- Auto close tags
        enable_rename = true, -- Auto rename pairs of tags
        enable_close_on_slash = false, -- Auto close on trailing </
      },
      -- Also override individual filetype configs, these take priority.
      -- Empty by default, useful if one of the "opts" global settings
      -- doesn't work well in a specific filetype
      per_filetype = {
        ['xml'] = {
          enable_close = true,
          enable_rename = true, -- Auto rename pairs of tags
        },
      },
      aliases = {
        ['conaryrecipe'] = 'xml',
      },
    }
  end,
```

**Comment by PriceHiller** [comment]
Hey @julianbopp can you give this another shot?

Some changes just hit main that *may* resolve this for you if it has the same root cause as #201.

**Comment by julianbopp** [comment]
Hey @PriceHiller, thanks for your reply. I updated the plugin and tried again but it still doesn't work :(

**Comment by BIIJESH** [comment]
Is it working for html ?
For me it is not working for html 
	{
		"windwp/nvim-ts-autotag",
		event = "InsertEnter",
		opts = {},
	},

**Comment by carljohnson93** [comment]
I have same issue.

**Comment by arminveres** [comment]
Hi there, do you have an update if this will get fixed?
