### ISSUE TITLE
Incompatibility with visual block mode on windows

### ISSUE THREAD

**Issue by Rahmyeon** [windwp/nvim-ts-autotag#216]
# Autotag conflict with visual block mode on windows
Hi, this may not get fixed as most nvim users are on Linux.
Autotag does work with visual block mode on windows (non-wsl).

# Reproducable steps
1. Have the default set up for auto-tag on Windows (as well as lazy loading = false)
2.  Use visual block mode with coding language (including HTML (don't know if it is a language or not)) that is compatible with autotag
3. Use insert mode with shift I or A to insert any text of your choosing
4. Press escape and the text should not complete properly as shown in the video below.
## This bug was found in windows terminal

https://github.com/user-attachments/assets/a3e4ed25-a6a7-48c0-84c1-714ef2d55a39

**Comment by Rahmyeon** [comment]
Ty for the amazing plugin btw!

**Comment by SagarChandra07** [comment]
try this

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive password: changeme

you may need to install the c compiler

**Comment by Rahmyeon** [comment]
What is this exactly?

**Comment by Rahmyeon** [comment]
Hey, checked the link today again and your account seems to banned?

**Comment by Rahmyeon** [comment]
I am opening this is a new issue because I got sent a mystery file that could be malware
