### ISSUE TITLE
Best way to use with auto save in conjunction prettier autoformatting

### ISSUE THREAD

**Issue by piersolenski** [windwp/nvim-ts-autotag#25]
I tend to use [Prettier](https://prettier.io/) to format my code via something like [Neoformat](https://github.com/sbdchd/neoformat), using [AutoSave](https://github.com/Pocco81/AutoSave.nvim). It works almost perfectly, however as this plugin triggers an AutoSave and thus code formatting via `InsertLeave` and `TextChanged` events, it kind of breaks the plugin for me by closing the tag immediately before I can populate it.

The only solution I've found so far is to turn off AutoSaving each time I want to change a tag, but that's a bit of a frustrating workflow.

I was thinking another way forward might be if AutoTag was able to call functions before and after it ran? That way it could disable something like AutoSave before it ran and reenable it afterwards.

I realise this is probably an issue that's out of the scope of what this library tries to solve using a more complex stack, but I was interested to know if you had any thoughts in regards to a workaround?

Thanks for your hard work!

**Comment by windwp** [comment]
i only use formatonsave and plugin formatter.nvim  have a code to detect buffer change when format.
it know a different of buffer after prettier format then it will not apply the format.
so maybe you can ask an author of autosave.nvim to increase delay and only save if buffer not change on delay time

**Comment by piersolenski** [comment]
AutoSave already has that debounce functionality, but it means hot reloading in the browser becomes very slow. They suggested adding a temporary abort function https://github.com/Pocco81/AutoSave.nvim/issues/12#issuecomment-922594676 - which I guess would be similar to disabling then reenabling the plugin as I mentioned before - would there be a way to call it with AutoTag before it ran?

**Comment by windwp** [comment]
you want to disable my plugin wait it save then format text and my plugin re enable and apply change then it will save and format again????
 it is a wrong process i will not do that. it is too many useless step there

**Comment by piersolenski** [comment]
I was thinking more of a general set of pre and post hooks that any user or plugin could reuse for a variety of use cases. No worries if you don't think it's a good idea, like I said before - it may be out of the scope of this plugin :-)

**Comment by Pocco81** [comment]
I second the idea of adding hooks. With it, the abort functionality for AutoSave could be used and it'd resolve this issue.

**Comment by piersolenski** [comment]
The ability to be able to toggle the plugin on and off would generally be really useful, and probably more within the scope of the plugin itself - as this is a feature common to most plugins 👌

**Comment by piersolenski** [comment]
Having thought about this a bit more, would it be possible to have options to enable/disable the auto close and auto rename functionality separately? That way you could close the tag manually or using a different plugin, but preserve the auto rename functionality.

**Comment by singlexyz** [comment]
I have the same problem.
My solution is to turn on auto-format by default and turn off auto-save.
When manually turning on auto-save, use the hook method to turn off auto-formatting. Close is the opposite.

```lua
local autosave = require("autosave")
autosave.hook_before_off = function()
  autoformat.attach()
end
autosave.hook_before_on = function()
  autoformat.detach()
  vim.lsp.buf.formatting_sync()
end
```

Automatic formatting is implemented using autocmd, and nvim already has a corresponding api.
```lua
-- autoformat
local M = {}

M.attach = function()
  local AutoFormatGroupId = vim.api.nvim_create_augroup("AutoFormatGroup", { clear = true })
  vim.api.nvim_create_autocmd({ "BufWritePre" }, {
    group = "AutoFormatGroup",
    pattern = {
      "*.js", -- ....
    },
    command = "lua vim.lsp.buf.formatting_sync()",
  })
end

M.detach = function()
  vim.api.nvim_del_augroup_by_name("AutoFormatGroup")
end

M.attach()

return M
```
