### ISSUE TITLE
Support php and blade files

### ISSUE THREAD

**Issue by rodrigore** [windwp/nvim-ts-autotag#26]
Hi! I was wondering if is possible to add support for laravel template engine (blade filetype) or how can I help to make it real?
Thanks for the plugin!

**Comment by codepuncher** [comment]
Hi @windwp, any chance we could revisit this?
Thanks

**Comment by ZayRTun** [comment]
Hello, any updates on this?
Thanks

**Comment by PriceHiller** [comment]
Hello, this should be resolved now with the merging of #173. If it doesn't work, please ping me and I'll reopen this issue.

**Comment by Dieal** [comment]
> Hello, this should be resolved now with the merging of #173. If it doesn't work, please ping me and I'll reopen this issue.
> 
> (As a part of @ydalton contributing to my fork, thanks)

Still doesn't work for me

**Comment by PriceHiller** [comment]
> > Hello, this should be resolved now with the merging of #173. If it doesn't work, please ping me and I'll reopen this issue.
> > (As a part of @ydalton contributing to my fork, thanks)
> 
> Still doesn't work for me

Can you supply an example? I can't really debug this issue otherwise.

**Comment by ydalton** [comment]
> Still doesn't work for me

Do you have the [Blade treesitter grammar](https://github.com/EmranMR/tree-sitter-blade) installed? 
You also need to have your injections and highlights configured correctly, otherwise HTML tags in Blade won't work.

**Comment by Dieal** [comment]
> > Still doesn't work for me
> 
> Do you have the [Blade treesitter grammar](https://github.com/EmranMR/tree-sitter-blade) installed? You also need to have your injections and highlights configured correctly, otherwise HTML tags in Blade won't work.

I tried installing it before, but I was unsuccessful. I added this to my config:
```lua
    config = function(_, opts)

      local parser_config = require("nvim-treesitter.parsers").get_parser_configs()

      parser_config.blade = {
        install_info = {
          url = "https://github.com/EmranMR/tree-sitter-blade",
          files = { "src/parser.c" },
          branch = "main",
        },
        filetype = "blade",
      }

      vim.filetype.add({
        pattern = {
          ['.*%.blade%.php'] = 'blade',
        },
      })

      -- [[ Configure Treesitter ]]
      -- See `:help nvim-treesitter`
      require('nvim-treesitter.configs').setup(opts)

    end
  },
```
and installed through TSInstall blade. The things I missed were the injections and the highlights, which I now configured by following [this](https://github.com/EmranMR/tree-sitter-blade/discussions/19#discussion-5400675) thread.
Now it works, sorry for the ignorance!
