### ISSUE TITLE
plugin doesnt work when lazy loaded at InsertEnter

### ISSUE THREAD

**Issue by siduck** [windwp/nvim-ts-autotag#28]
The plugin doesnt work when loaded at InsertEnter , 

```
 use {
      "windwp/nvim-ts-autotag",
      event = "InsertEnter",
      config = function()
         require("nvim-ts-autotag").setup()
      end,
   }
   ```
   
But it works if i replaced the event with after = "nvim-treesitter" , Also the :PackerStatus does show that the plugin has been loaded but the autocompletion of auto-close tag doesnt work :/

**Comment by santigo-zero** [comment]
In my case it happens when using `event = "BufRead"` to lazyload treesitter, the auto-close tag doesn't work, if I don't lazyload any of the two plugins it works properly.

**Comment by siduck** [comment]
@windwp can you look onto this issue? :c

**Comment by windwp** [comment]
sorry for the long response but it depend on treesitter call a module.  event insertenter  happen after tree sitter call a module.
i can lazyload by filetype.

**Comment by siduck** [comment]
> sorry for the long response but it depend on treesitter call a module. event insertenter happen after tree sitter call a module. i can lazyload by filetype.

Lazyload at filetype? How do you do it even if treesitter is lazyloaded , like how do you get a list of filenames which need certain treesitter parsers

**Comment by windwp** [comment]
i don't use packer but packer have that
