### ISSUE TITLE
jsx/js

### ISSUE THREAD

**Issue by kyazdani42** [windwp/nvim-ts-autotag#3]
Hi,
i tried this, works perfectly with HTML, but:
- js: doesn't close tags at all
- jsx: closes the tag that closes (`<div></div>|OUTPUTS HERE`)
- tsx: same as jsx
to reproduce: simply open a file and `const a = () => <div>` nothing happens.
I could debug this but this seems like quite an issue to me. Or maybe something went wrong with my setup.

I use the latests versions of neovim, nvim-treesitter and nvim-ts-autotag, loaded through packer without extra arguments.

**Comment by windwp** [comment]
can you get a latest version and check again

**Comment by windwp** [comment]
if you want to work on js or ts file you should set filetype to javascriptreact or typescriptreact

**Comment by windwp** [comment]
@kyazdani42  now it work on js file

**Comment by kyazdani42** [comment]
works now thanks :)

**Comment by leatfingies** [comment]
Hi @windwp, thanks for the plugin. I'm having an issue with `typescriptreact` filetype. For some reason, it doesn't insert the close tag in tsx files (works fine with js and html). Is there any way I can debug this to figure out what went wrong? I didn't override the default values btw.

**Comment by leatfingies** [comment]
I played with the config a bit more, it works in tsx files as expected when I use the setup function
```
require('nvim-ts-autotag').setup()
```
Doesn't work when I do this

```
require'nvim-treesitter.configs'.setup {
  autotag = {
    enable = true,
  }
}
```

**Comment by joemas08** [comment]
In my packer config file I added `use 'windwp/nvim-ts-autotag'` and I got it to work for me after a `:PackerSync`.
