### ISSUE TITLE
Does not work in template literals of JS/TS files

### ISSUE THREAD

**Issue by benfrain** [windwp/nvim-ts-autotag#32]
Treesitter understands nested tags in Template Literals but I can't get auto-tag to see them (working fine in HTML files)

Example - typing standard js file:

```js
const ex = html`<div>|`
```

Would expect:

```js
const ex = html`<div>|</div>`
```

Actually get:

```js
const ex = html`<div>|`
```

Possibly related to #21

**Comment by colepeters** [comment]
Sorry to bump an old issue, just wondering if there's any chance for an update here? @bennypowers suggests this should be possible, and with JS functions returning HTML templates becoming more common, this would be a great quality of life improvement! :)

**Comment by bennypowers** [comment]
see #78 which fixes this

**Comment by colepeters** [comment]
Wow that was fast, many thanks @bennypowers! Fingers crossed for a merge on this soon.

**Comment by bennypowers** [comment]
sure thing
use my fork in the mean time

```lua
use { 'bennypowers/nvim-ts-autotag', { branch = 'template-tags' } }
```

**Comment by benfrain** [comment]
@windwp would you be able to merge this in?

**Comment by marlun** [comment]
I'm also using this and would really appreciate it getting in, I'm using the bennypowers branch for now though and it's working great.
