### ISSUE TITLE
Error running config for nvim-ts-autotag: [string "..."]:0: loop or previous error loading module 'nvim-ts-autotag'

### ISSUE THREAD

**Issue by nyngwang** [windwp/nvim-ts-autotag#33]
As title, I'm using Packer.nvim and I got error:

```
Error running config for nvim-ts-autotag: [string "..."]:0: loop or previous error loading module 'nvim-ts-autotag'
```

**Comment by issadarkthing** [comment]
How to ensure the treesitter loading first?

**Comment by nyngwang** [comment]
@issadarkthing: Try packer.nvim `requires`~

**Comment by issadarkthing** [comment]
It doesn't work. This is my current setup for `nvim-ts-autotag`
```
  use { 
    'windwp/nvim-ts-autotag', 
    opt = true, 
    ft = 'typescriptreact', 
    requires = {{'nvim-treesitter/nvim-treesitter'}},
    config = function() require('nvim-ts-autotag').setup() end,
  }
```

**Comment by nyngwang** [comment]
@issadarkthing: I was busying clean out issues. Then you can try mine, which __has to__ work :)

```lua
  use {
    'windwp/nvim-ts-autotag',
    branch = 'main',
    requires = {
      'nvim-treesitter/nvim-treesitter',
    },
    config = function ()
      require('nvim-ts-autotag').setup()
    end
  }
```

**Comment by issadarkthing** [comment]
The error is gone now but it still doesn't auto-complete

**Comment by nyngwang** [comment]
@issadarkthing: I think the problem is on `'nvim-treesitter/nvim-treesitter'`. You will need to add a standalone `use { ... }` for `'nvim-treesitter/nvim-treesitter'`. I can provide you my config after work.

**Comment by issadarkthing** [comment]
Alright sure
