### ISSUE TITLE
does not work auto close tag

### ISSUE THREAD

**Issue by ShiChenCong** [windwp/nvim-ts-autotag#34]
does not work
here is my minimum config
```
init.vim
  Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
  Plug 'windwp/nvim-ts-autotag'
after/plugin/autotag.rc.lua
  require'nvim-treesitter.configs'.setup {
  autotag = {
    enable = true,
  }
}
vim.lsp.handlers['textDocument/publishDiagnostics'] = vim.lsp.with(
    vim.lsp.diagnostic.on_publish_diagnostics,
    {
        underline = true,
        virtual_text = {
            spacing = 5,
            severity_limit = 'Warning',
        },
        update_in_insert = true,
    }
)
require('nvim-ts-autotag').setup()

```
when i type `>` after `<div`, does not auto add `</div>`， below is tsx file
![image](https://user-images.githubusercontent.com/22486446/140603376-b0409702-4056-43d1-80f7-1e2d8e5931df.png)

**Comment by windwp** [comment]
check nvim treesitter readme and makesure you install language

**Comment by ShiChenCong** [comment]
for anyone meet this problem, you may forget to `:TSInstall <language_to_install>`, install your language, eg:  `:TSInstall tsx`
