### ISSUE TITLE
[Feature request] <c-a> and <c-x> keybinding 

### ISSUE THREAD

**Issue by Tus1688** [windwp/nvim-ts-autotag#35]
Hi, thank you for making neovim accesible for Jsx/Tsx user.

I love the way it automatically rename tag with insert mode 
`<h1|> </h1>`
`<h|> </h1>`
`<h2|> </h2>`

But,
`<h|1|> </h1>`  then  `<c-a>` which increment number by 1 
`<h2> </h1>`

I didn't find it working. Is there any way around to achieve that? Thanks in advance :+1:

**Comment by Davincible** [comment]
@windwp please :)))
