### ISSUE TITLE
Doesn't work with html files

### ISSUE THREAD

**Issue by StitiFatah** [windwp/nvim-ts-autotag#36]
Version : NVIM v0.6.0

OS : Archlinux
  
My installed plugins : 
```
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}  " We recommend updating the parsers on update
Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app && yarn install'  }
Plug 'preservim/nerdcommenter'
Plug 'vim-airline/vim-airline'
Plug 'ryanoasis/vim-devicons' 
Plug 'mattn/emmet-vim' 
Plug 'tpope/vim-eunuch' 
Plug 'wfxr/minimap.vim'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'jiangmiao/auto-pairs'
Plug 'windwp/nvim-ts-autotag'
Plug 'andymass/vim-matchup'
Plug 'ggandor/lightspeed.nvim'
Plug 'tpope/vim-surround'
```

I'm using the default config and It works well with .js .jsx and .tsx files but not with .html ones even when explicitly  adding 'html' to filetypes.
Any ideas ? Thanks in advance.

**Comment by mgeist** [comment]
Was able to get this working with `:TSUpdate html` which manually installed an HTML parser.  Not sure if there's an automate way to do that yet, but it solved the issue for now.

**Comment by StitiFatah** [comment]
> Was able to get this working with `:TSUpdate html` which manually installed an HTML parser. Not sure if there's an automate way to do that yet, but it solved the issue for now.

Can confirm it works. I rarely use bare html files and thus didn't think about installing an html parser when installing treesiter.

**Comment by gegoune** [comment]
You need html parser even if you are using it as embedded language (injected) in Vue, etc.

**Comment by StitiFatah** [comment]
> You need html parser even if you are using it as embedded language (injected) in Vue, etc.

I'm mostly using JSX that's why.
