### ISSUE TITLE
support for django (htmldjango)?

### ISSUE THREAD

**Issue by shaeinst** [windwp/nvim-ts-autotag#48]

**Comment by shket-228** [comment]
Still have this problem (nvim v0.7).
Have `filetypes = { "htmldjango", ...` in config files.
It seems to be trying to do something, considering mode indicator blinking.
![Peek 2022-05-13 00-34](https://user-images.githubusercontent.com/55373470/168173377-b0349d50-b890-4f96-9a94-e48ddab89355.gif)
I really love this plugin, but this issue makes me disappointed.

**Comment by shket-228** [comment]
Still have this problem (nvim v0.7).
Have `filetypes = { "htmldjango", ...` in config files.
It seems to be trying to do something, considering mode indicator blinking.
![Peek 2022-05-13 00-34](https://user-images.githubusercontent.com/55373470/168173377-b0349d50-b890-4f96-9a94-e48ddab89355.gif)
I really love this plugin, but this issue makes me disappointed.

**Comment by yujinyuz** [comment]
I also have the same experience with @shket-228

**Comment by ambadyanands** [comment]
Confirming that the issue still persists, it'd be good to reopen the issue. Or should I create a new one?

**Comment by shaeinst** [comment]
are you sure guys? try as following config

```lua
-- enable html parser in htmldjango file
local import_parsers, parsers = pcall(require, 'nvim-treesitter.parsers')
if import_parsers then
	local parsername = parsers.filetype_to_parsername
	parsername.htmldjango = 'html' 
end


local import_tag, autotag = pcall(require, "nvim-ts-autotag")
if not import_tag then return end
autotag.setup({
	autotag = {
		enable = true,
	},
	filetypes = {
		'html', 'htmldjango',
	},
})
 ```

**Comment by ambadyanands** [comment]
@shaeinst Thanks a lot, enabling html parser for `htmldjango` filetype did the trick.

I think [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) should do this by default. Will try opening an issue there, thanks again.

**Comment by comiluv** [comment]
I'm still having problems.
I already have filetypes = { 'htmldjango', 'html', ... } in nvim-treesitter config.
I tried both `lua require"nvim-treesitter.parsers".filetype_to_parsername.htmldjango = 'html'` and `lua vim.treesitter.language.register("html", "htmldjango")` but none of these worked.
Only way I could get autotag to work is to `set ft=html` but this would cause LSPs to fail.

**Comment by shaeinst** [comment]
for `neovim >= 0.9`
```lua
-- safely import tree-sitter
local treesitter_imported_ok, treesitter =  pcall(require, 'nvim-treesitter.configs')
if not treesitter_imported_ok then return end


local register = vim.treesitter.language.register
register('html', 'htmldjango') -- enable html parser in htmldjango file
```

```lua

local import_tag, autotag = pcall(require, "nvim-ts-autotag")
if not import_tag then return end
autotag.setup({
	autotag = {
		enable = true,
	},
	filetypes = {
		'html', 'htmldjango',
	},
})
```

[reference](https://github.com/Abstract-IDE/Abstract/blob/fe07dc51658aeb93b636e3dda62c2f1ed0cfc8e3/lua/plugins/nvim-treesitter.lua#L18-L23)

**Comment by Coleej** [comment]
@shaeinst , don't you lose syntax highlighting for the templating aspects of the htmldjango file?

**Comment by an4s911** [comment]
Does this have a fix yet?

I am still facing the same issue. I tried all the solutions mentioned above in this thread. None of them worked.

**Comment by aketawi** [comment]
Not sure what exactly this entails since I don't have much experience in Lua, but:
After hacking around for a little while I've found that removing "htmldjango" from the `HBS_TAG.filetypes` seems to do the trick. Perhaps it's overwriting the definition in `HTML_TAG`?

https://github.com/windwp/nvim-ts-autotag/blob/531f48334c422222aebc888fd36e7d109cb354cd/lua/nvim-ts-autotag/internal.lua#L69
It was last changed in this commit: https://github.com/windwp/nvim-ts-autotag/commit/25698e4033cd6cd3745454bfc837dd670eba0480 and I can't find the reason why.

Dunno if we should file this as a bug or if this has a reason to exist, but for the time being, to enable django support you can just remove it on line 69 of `lua/nvim-ts-autotag/internal.lua`. 

@an4s911 @comiluv @shk3t @shaeinst you might find this helpful.

**Comment by Alan-Manning** [comment]
i still cannot get this working, i have tried all of the above and nothing. If anybody has fixed please post
