### ISSUE TITLE
Always getting two >> at the closing tag

### ISSUE THREAD

**Issue by weilbith** [windwp/nvim-ts-autotag#5]
Hi :wave: 
I just installed your plugin and tried it out. Unfortunately I always get two `>` for the closing tag. So if I just open a test file like `test.html` and then type `<body`. Now if I hit `>` the result is the following `<body></body>>`. Why?

**Comment by windwp** [comment]
Do you use another plugin ?
it is work with minimal.vim on test
https://github.com/windwp/nvim-ts-autotag/blob/main/tests/minimal.vim

**Comment by weilbith** [comment]
Hmm. Good point. I need to check if a language server is doing is doing some snippet like stuff. But I actually though they get applied only on confirmation. Anyway, thanks for the minimal config. I'll see what causes the issue.

**Comment by cloggier** [comment]
@weilbith I am affected by the same issue. Did you manage to fix it maybe?

**Comment by weilbith** [comment]
Sorry,  but I haven't worked recently much with such filetypes. So I lost focus of it. I haven't did any further in investigation since the last comment. If you find something, I'm happy to get notified. :upside_down_face:
