### ISSUE TITLE
Problem with nested divs

### ISSUE THREAD

**Issue by heimer16** [windwp/nvim-ts-autotag#54]
```
<div></div>  <--- if I replace the opening "div" with "span" it changes the closing tag as expected.

<div>
  <div></div>  <--- if I replace the opening "div" with "span" it does not update the closing tag.
</div>
```

**Comment by sungkang** [comment]
this applies to any matching tag

**Comment by dpetka2001** [comment]
I have the same problem. I would appreciate an answer if it's something fixable or not instead of a stale-bot just closing a valid issue due to inactivity. At least leave it open. Closing issues due to inactivity especially when there's no response from the maintainer himself should be discouraged.
