### ISSUE TITLE
internal.lua throw an index error

### ISSUE THREAD

**Issue by mohammad5305** [windwp/nvim-ts-autotag#58]
![image](https://user-images.githubusercontent.com/71145952/163809700-373e14c1-3b2b-4836-8d3d-42de715825e6.png)

![image](https://user-images.githubusercontent.com/71145952/163809854-a9c98446-9daa-4e57-bee9-e15c4929a915.png)

I'm getting this error when I came to packer and install the latest commit of treesitter and nvim-ts-autotag 

neovim 0.7v

**Comment by luisiacc** [comment]
Same here, probably something to do with lastest breaking changes on nvim-treesitter: https://github.com/nvim-treesitter/nvim-treesitter/issues/2293#issuecomment-1101356273

**Comment by bushblade** [comment]
I'm seeing this too.

**Comment by VuongTran21** [comment]
I have same issue

**Comment by VuongTran21** [comment]
> ![image](https://user-images.githubusercontent.com/71145952/163809700-373e14c1-3b2b-4836-8d3d-42de715825e6.png)
> 
> ![image](https://user-images.githubusercontent.com/71145952/163809854-a9c98446-9daa-4e57-bee9-e15c4929a915.png)
> 
> I'm getting this error when I came to packer and install the latest commit of treesitter and nvim-ts-autotag
> 
> neovim 0.7v

for the error `ts_utils.get_node_text`, you can fix follow [this link](https://www.reddit.com/r/neovim/comments/u6eu0q/treesitter_breaking_plugins/)

**Comment by mohammad5305** [comment]
> > ![image](https://user-images.githubusercontent.com/71145952/163809700-373e14c1-3b2b-4836-8d3d-42de715825e6.png)
> > ![image](https://user-images.githubusercontent.com/71145952/163809854-a9c98446-9daa-4e57-bee9-e15c4929a915.png)
> > I'm getting this error when I came to packer and install the latest commit of treesitter and nvim-ts-autotag
> > neovim 0.7v
> 
> for the error `ts_utils.get_node_text`, you can fix follow [this link](https://www.reddit.com/r/neovim/comments/u6eu0q/treesitter_breaking_plugins/)

thanks but I would be more happier if plugin update his code, so I will keep open this issue

**Comment by bushblade** [comment]
Yeah I tried the solution in the Reddit post, but it did not work for me.

**Comment by bushblade** [comment]
I think this can be closed now after #60 ?
All good for me again, thanks.

**Comment by mohammad5305** [comment]
yes it working now thanks

**Comment by VuongTran21** [comment]
> yes it working now thanks

hi @mohammad5305 , how can you fix it? I'm still facing with this issue.

**Comment by bushblade** [comment]
@VuongTran21 Just need to update your plugins.

**Comment by VuongTran21** [comment]
beautiful, it worked! thanks @bushblade
