### ISSUE TITLE
Unable to insert close tag?

### ISSUE THREAD

**Issue by mnarrell** [windwp/nvim-ts-autotag#7]
Plugin installed and configured as:

```
use {'windwp/nvim-ts-autotag', config = function() require('nvim-ts-autotag').setup() end}
```
Buffer with `xml` filetype and contents:

```
<?xml version="1.0" encoding="UTF-8"?>
<xml
```

Adding close bracket does not complete the end tag.

**Comment by windwp** [comment]
Sorry it is my mistake I only check in html and think xml is same but i just check nvim-treesitter don't include parser for xml language.
I just remove xml and update readme. I will update it when nvim-treesitter incude xml.
Thank
