### ISSUE TITLE
Not working with react fragments (empty tags)

### ISSUE THREAD

**Issue by pedro757** [windwp/nvim-ts-autotag#70]
In react we use fragments, which is basically just an empty tag like this:

```jsx
function HolaWindwp() {
  return (
    <>
    // Children
    </>
  )
}
```

If i try to chage that empty tag this plugin does nothing.

```jsx
<div>

</> // it doesn't autotag here
```

It works well with non-empty tags.

**Comment by kutsan** [comment]
I hate stale bot. This needs to re-opened.
