### ISSUE TITLE
Autorename on .tsx files does not work

### ISSUE THREAD

**Issue by juhaku** [windwp/nvim-ts-autotag#71]
Hello, Typing `<div` and then `>` will result `<div></div>` It works fine, but when renaming the field it doesn not work. When typing `ciwspan<Esc>` within the `<div>` does not result `<span></span>` but results only `<span></div>`. 

Also when closing single type with slash `/` it does not add `>` the the end. Expected behaviour when typing `<div` and then `/` the close  tag `>` should be automatically appended. 

Also has noted here https://github.com/alvan/vim-closetag/issues/76 When editing `tsx` or `jsx` and using jsx and tsx react elements with `<></>` it does not automatically end or rename the tag either. When typed `<` and then closed with `>` it will not automatically add `</>` end tag.

**Comment by shaeinst** [comment]
it's working fine for me.
have a look at my config
[packer](https://github.com/Abstract-IDE/Abstract/blob/90828818b2e975ca97b7416123aef1fe17fa5691/lua/packer_nvim.lua#L148-L154)
[treesitter](https://github.com/Abstract-IDE/Abstract/blob/main/lua/plugins/nvim-treesitter.lua)
[ts-autotag](https://github.com/Abstract-IDE/Abstract/blob/main/lua/plugins/nvim-ts-autotag.lua)

**Comment by juhaku** [comment]
The configs where not much different from mine. However I have previously not used `<Esc>` key but I prefer typing `<C-c>`. I know ctrl + c is command cancel in neovim but I find it more intuitive than reaching out to the `<Esc>` or remapping `<Esc>` to some other key combination, because I want the pressing of `<Esc>` to constant across the modes.

So as I have found out:
- Typing `<div` an  then `>` will result `<div></div>`
- Typing `ciwspan<Esc>` within div results `<span></span>`
  - But typing `ciwspan<C-c>` will **not** work and will result `<span></div>`
- Typing `<>` will **not** autoclose `</>` jsx / tsx empty elements. 
- Also typing `<div` and then `/` will **not** close with `>`, so end result will be `<div/` **not** `<div/>`

Is there a way to make the counterpart element update while typing within the element? The way pretty much any IDE does it?

**Comment by shaeinst** [comment]
you can use [nvim-autopairs](https://github.com/windwp/nvim-autopairs) plugin for such task
for example:

>Typing <> will not autoclose </> jsx / tsx empty elements.
```lua
require('nvim-autopairs').add_rules {
    Rule("%<%>$", "</>", { 'typescript', 'typescriptreact', 'javascript', 'javascriptreact' })
            :use_regex(true),
}
```

**Comment by juhaku** [comment]
Thanks, that fixes the empty tsx element issue, but still the behavior is lacking in other aspects.

**Comment by shaeinst** [comment]
i am not trying to convince you but using `<C-c>` instead of `ESC` seems little weird to me. since `ESC` is one of the important key in vim, i would suggest you to swap `ESC` with `Caps Lock`. Then it would become more easy to use ESC (since you left hand fingers is always close to a,s,d,f).
i use [keyd](https://github.com/rvaiya/keyd) to swap keys..

**Comment by pradana4648** [comment]
You should install this too
```:TSInstall tsx```
and after that is work fine

**Comment by juhaku** [comment]
> You should install this too
> :TSInstall tsx

Yes sure, it is installed

**Comment by waseidel** [comment]
> You should install this too `:TSInstall tsx`
> 
> Duplicate from #66

That fixed for me, at least autoclosing jsx tags
