### ISSUE TITLE
Add eruby support

### ISSUE THREAD

**Issue by mario-amazing** [windwp/nvim-ts-autotag#73]
Could you add to supported languages `eruby`?
Thanks in advance

**Comment by bluz71** [comment]
Fundamentally, Neovim Treesitter needs to add native `eruby` support as noted in [this issue](https://github.com/nvim-treesitter/nvim-treesitter/issues/1352).

If/when that happens, then `eruby` support should be easy to add here; but only after [nvim-treesitter issue 1352](https://github.com/nvim-treesitter/nvim-treesitter/issues/1352) is done.
