### ISSUE TITLE
Autorename not working

### ISSUE THREAD

**Issue by MatMatias** [windwp/nvim-ts-autotag#75]
Autorename is not working for me.

For example: when I'm inside a `<div>` tag and type ciwspan`<Esc>` it just rename the first `<div>` tag to span, and the other tag remains as `</div>`.

I've tested it on .tsx and .html files.

Here is my config:
[Treesitter](https://github.com/MatMatias/nvim-config/blob/master/lua/treesitter-config/init.lua)
[Packer](https://github.com/MatMatias/nvim-config/blob/master/lua/packer-config/init.lua)

**Comment by PaulKushch** [comment]
@MatMatias Any solutions on this? Have the same problem. Best regards

**Comment by MatMatias** [comment]
@PaulKushch not yet.

**Comment by PaulKushch** [comment]
Solved for me to install tsx for treesitter config:)

**Comment by stefanwatt** [comment]
For me it does work in HTML but not in Svelte.
Treesitter parser for svelte is installed.

**Comment by MatMatias** [comment]
@PaulKushch tsx for treesitter is installed here, and yet it does not work. :/
