### ISSUE TITLE
Disable automatic renaming

### ISSUE THREAD

**Issue by amarakon** [windwp/nvim-ts-autotag#80]
I do not want HTML tags to automatically rename themselves but I want them to automatically close. How can I do this?

**Comment by sifu** [comment]
I have a PR that would allow you to disable the automatically renaming via
```
require("nvim-ts-autotag").setup({
	enable_rename = false,
})
```
until the PR https://github.com/windwp/nvim-ts-autotag/pull/83 is merged, you could use my fork:
https://github.com/sifu/nvim-ts-autotag
