### ISSUE TITLE
Is there a way to treat eruby files as eruby + html just for autotags?

### ISSUE THREAD

**Issue by nickjj** [windwp/nvim-ts-autotag#85]
Hi,

If I open a Rails app that uses erb templates, the file is detected as `eruby` and everything looks really nice.

However if you type `<p>` then it will not close the `</p>`. If you set `set ft=html` on the file then it looks off but `<p>` will correctly get closed with `</p>`. Setting the ft to `eruby.html` goes back to looking good but autotags don't work.

Is there custom configuration that can be done to say "make it look good by correctly using the correct TS file type but also allow autotags to treat this file as both eruby and html"?

**Comment by Slotos** [comment]
Try `TSInstall embedded_template`.

**Comment by nickjj** [comment]
I ran that command and re-opened nvim, it didn't change the outcome. The file type was detected as `eruby` and tags didn't get auto-closed.

Is there anything I would need to configure beyond that to use `embedded_template`?

**Comment by Slotos** [comment]
Apologies for the long wait. Here's a diff that makes this plugin support embedded_template:

```
diff --git a/lua/nvim-ts-autotag/internal.lua b/lua/nvim-ts-autotag/internal.lua
index ab3e572..8d1da2c 100644
--- a/lua/nvim-ts-autotag/internal.lua
+++ b/lua/nvim-ts-autotag/internal.lua
@@ -11,7 +11,8 @@ M.tbl_filetypes = {
     'php',
     'markdown',
     'glimmer','handlebars','hbs',
-    'htmldjango'
+    'htmldjango',
+    'embedded_template',
 }
```

Set up with:

```lua
    autotag = {
      enable = true,
      filetypes = { "html" , "xml", "eruby" }, -- eruby is what matters, the rest you just might want to have enabled too
    },
```

**Comment by nickjj** [comment]
Thanks, I applied those patches and I'm getting interesting behavior.

For example:

- If open a file called `_form.html.erb`, the file type is set as `eruby` and typing `<p>` does auto-close that tag
- If I open any other eruby file, typing `<p>` does not auto-close the tag (`:vsplit` on the same file will still work tho)
- Whether or not I type `<p>` into the first file, the second file will never auto-close the tag

I have to fully close neovim and re-open it have auto-close tag work on a single file and the pattern repeats itself.

There's no errors being printed in a way that I can see.

**Comment by Slotos** [comment]
Use `filetypes = { "html" , "xml", "eruby", "embedded_template" },`
This relates to default filetypes values and execution order.

Basically, the first attach call from nvim-treesitter works with default data (that's why patch to the plugin code was needed). But then the third line of `attach` function calls `setup` that replaces `internal.tbl_filetypes` with data you provide in nvim-treesitter setup. And that doesn't include `embedded_template`, leading to tree-sitter skipping attach calls due to `internal.is_supported` reporting that the language is no longer supported.

**Comment by Slotos** [comment]
By the way, this bug only affects treesitter setup use style.

If you opt for `require('nvim-ts-autotag').setup({ filetypes = { "html" , "xml", "eruby", "embedded_template" } })` instead, you should be seeing the desired behaviour without any patches.

**Comment by nickjj** [comment]
Thanks. I tried out the first solution (with the patch) and it works.

Of the 2 solutions which is preferred? For example is one faster than the other for processing the file, etc.?

For the non-patch version do I need to set up `nvim-ts-autotag` using that setup function along with removing `autotag.filetypes` from the treesitter's setup function? I can test this but wanted to ask openly in case someone else runs into this.

**Comment by Slotos** [comment]
Generally, treesitter setup route is the common one. If at any point nvim-treesitter changes attach routine, it will handle it without the need to update this plugin. And with this plugin being fully dependent on nvim-treesitter, I can't come up with the reason to separate the two.

`require('nvim-ts-autotag').setup` basically sets up autocommands equivalent to those that nvim-treesitter adds.

I didn't notice anything that would make one faster than the other.

**Comment by nickjj** [comment]
Ok. If that's the case, does that mean we'll want to modify this plugin based on your original patch? The one where you added `embedded_template` to `M.tbl_filetypes`.

**Comment by Slotos** [comment]
I'd refactor `tbl_filetypes` entirely, turning it into a set of `{"vim_ft", "ts_language"}` tuples, with a single string shorthand akin to `"html"` being treated as `{"html", "html"}`. And I'd remove `setup` initialization route entirely.

Might write a PR for that that in a week or two, once my employment is decided.

**Comment by nickjj** [comment]
Ok, I'll keep an eye out for that. In the mean time I'll keep this current patch active.

Thanks a lot for the help! Having auto-closing tags that works well is a huge quality of life improvement.

**Comment by bluz71** [comment]
> ```
> diff --git a/lua/nvim-ts-autotag/internal.lua b/lua/nvim-ts-autotag/internal.lua
> index ab3e572..8d1da2c 100644
> --- a/lua/nvim-ts-autotag/internal.lua
> +++ b/lua/nvim-ts-autotag/internal.lua
> @@ -11,7 +11,8 @@ M.tbl_filetypes = {
>      'php',
>      'markdown',
>      'glimmer','handlebars','hbs',
> -    'htmldjango'
> +    'htmldjango',
> +    'embedded_template',
>  }
> ```

Hello,

The above patch works well with Ruby-on-Rails `erb` templates.
Is there any reason why this can't be incorporated into `nvim-ts-autotag` now?
I can make a PR if needed.
I would like to see this push forward.

Best regards.

**Comment by bluz71** [comment]
Please don’t close, some of us want this.

**Comment by pseudogram** [comment]
I wanted a config that allowed this plugin to work in a an `erb` or `html` file. With all the advice above I couldn't figure out why it wouldn't work for me. 

Here is minimal [Lazy](https://lazy.folke.io/) config that allows autotags to work with `.html.erb` (embedded ruby files)

First, Treesitter:
```lua
return {
    'nvim-treesitter/nvim-treesitter',
    config = function()
        require 'nvim-treesitter.configs'.setup {
             ensure_installed = {"html", "embedded_template" },
        }
    end,
    dependencies = {
        'windwp/nvim-ts-autotag' -- Without this dependency set, auto tag completion would not work... for me
    },
}
```

Next, Autotag:
```lua
return {
    'windwp/nvim-ts-autotag',
    config = function()
        require('nvim-ts-autotag').setup({})
    end,
}
```

Now. If you're you're following along with the the thread above OR the [thread "Dont work."](https://github.com/windwp/nvim-ts-autotag/issues/64), this excludes a lot of notes that while experimenting proved useless. Here is my final config, with useless comments included.


```lua
return {
    'nvim-treesitter/nvim-treesitter',
    build = function()
        require("nvim-treesitter.install").update({ with_sync = true })()
    end,
    lazy = false,
    config = function()
        require 'nvim-treesitter.configs'.setup {
            -- A list of parser names, or "all" (the five listed parsers should always be installed)
            ensure_installed = { "c", "lua", "vim", "vimdoc", "query", "python",
                "css", "javascript", "typescript", "ruby", "html", "xml",
                "embedded_template" },
            -- autotag = {
            --     enable = true,
            -- },
        }
    end,
    dependencies = {
        -- "RRethy/nvim-treesitter-endwise", -- Needed to prevent treesitter ident issue with Ruby: https://github.com/tree-sitter/tree-sitter-ruby/issues/230#issuecomment-1312403487
        'windwp/nvim-ts-autotag'
    },
}
return {
    'windwp/nvim-ts-autotag',
    config = function()
        require('nvim-ts-autotag').setup({
            opts = {
                enable_close = true,          -- Auto close tags
                enable_rename = true,         -- Auto rename pairs of tags
                enable_close_on_slash = true -- Auto close on trailing </
            },
        })
    end,
    -- lazy = true,
    -- event = "VeryLazy",
}
```

> NVIM v0.10.0
> Build type: Release
> LuaJIT 2.1.1716656478
> Run "nvim -V1 -v" for more info
> 
> [nvim-treesitter - 2024/06/24 - d4a888ae3cff358cb239643c45b2b38bb60e29c6](https://github.com/nvim-treesitter/nvim-treesitter/commit/d4a888ae3cff358cb239643c45b2b38bb60e29c6)
> [nvim-ts-autotag - 2024/06/21 - ddfccbf0df1b9349c2b9e9b17f4afa8f9b6c1ed1](https://github.com/windwp/nvim-ts-autotag/commit/ddfccbf0df1b9349c2b9e9b17f4afa8f9b6c1ed1)
