### ISSUE TITLE
Close tag after inputting / 

### ISSUE THREAD

**Issue by kuchejak** [windwp/nvim-ts-autotag#94]
Hello, I love this plugin. The only feature I miss (coming from WebStrom) is the ability to close tag just by inputting  `/` - for example I have `<Image ` and when I press `/` I would like to get `<Image />`, but I get just `<Image /`.

Is this somehow configurable with this plugin? If not, would you consider adding it?

Thank you

**Comment by Niezzx** [comment]
The same problem occurs in React. I would really like the author can add this feature.

**Comment by gungun974** [comment]
It's still a bit sad to see that the robot declared this ticket as stale when I opened a pull request to normally solve this problem. 
I hope the same will not happen to my pull request :sweat_smile: 
(Let no one say say anything for 30 days and my PR is auto close by a bot)

**Comment by gungun974** [comment]
So just I want to say it in case the information was missing but normally @kuchejak and @yuniezzx this feature have been integrated since e254b306fb81ed69049cce526e7906150d73e0d1.

This issue therefore can be closed normally.

**Comment by ogios** [comment]
sorry, it doesn't work for me in .vue file, i'm currently writing vue project using volar lsp and nvchad, here's my setup:
```lua
  {
    "nvim-treesitter/nvim-treesitter",
    -- dependencies = {
    --   require "custom.configs.plugins.ts-autotag_conf",
    -- },
    opts = {

      highlight = {
        enable = true,
        use_languagetree = true,
      },

      ensure_installed = {
        -- defaults
        "vim",
        "lua",

        -- web dev
        "html",
        "css",
        "javascript",
        "typescript",
        "tsx",
        "json",
        "vue",
        -- "svelte",

        -- low level
        "python",
        "java",
        "go",
      },
      indent = {
        enable = true,
      },
      -- autotag = {
      --   enable = true,
      --   enable_rename = true,
      --   enable_close = true,
      --   enable_close_on_slash = true,
      -- },
    },
  },

...

  { import = "custom.configs.plugins.ts-autotag_conf" },

...

}

```

```lua
return {
  "windwp/nvim-ts-autotag",
  dependencies = "nvim-treesitter/nvim-treesitter",
  config = function()
    require("nvim-ts-autotag").setup()
  end,
  lazy = true,
  event = "VeryLazy",
}

```

i've tried both ways to setup, but none of them works.
